version: '3.3'
services:
  web:
    build:
      context: ./image
      dockerfile: Dockerfile
    container_name: myWildfly
    environment:
      - WILDFLY_USER=Camilo
      - WILDFLY_PASS=kagx25pass
      - DB_NAME=prueba
      - DB_USER=Camilo
      - DB_PASS=kagx25pass
      - DB_URI=db:3306
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./main
        target: /opt/jboss/wildfly/modules/system/layers/base/com/mysql/main
    ports:
      - 8080:8080
      - 9990:9990
  db:
    container_name: myDataBase
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: Camilo
      MYSQL_PASSWORD: kagx25pass
    ports:
      - 6033:3306
networks:
    default:
        driver: bridge
